"use client";

import React, { useEffect, useState } from 'react';
import { Activity, AlertTriangle, ArrowRight, BarChart3, Bus, CalendarDays, Check, ChevronDown, CircleDollarSign, Clock3, Download, Edit3, FileText, LayoutDashboard, Map, Plus, Route, Search, Settings, ShieldCheck, Trash2, TrendingUp, UserRound, Users, X } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

type Tab = 'Dashboard' | 'Fleet Management' | 'Routes & Stops' | 'Drivers' | 'Schedules' | 'Reports' | 'System Settings';
type VehicleStatus = 'Active' | 'En Route' | 'Maintenance';
type Vehicle = { id: string; plate: string; type: string; seats: number; status: VehicleStatus };

type Driver = { name: string; id: string; phone: string; expiry: string; route: string; duty: 'On Shift' | 'Off Duty'; rating: string };

const tabs: { label: Tab; icon: React.ReactNode }[] = [
  { label: 'Dashboard', icon: <LayoutDashboard size={19} /> }, { label: 'Fleet Management', icon: <Bus size={19} /> }, { label: 'Routes & Stops', icon: <Map size={19} /> }, { label: 'Drivers', icon: <Users size={19} /> }, { label: 'Schedules', icon: <CalendarDays size={19} /> }, { label: 'Reports', icon: <BarChart3 size={19} /> }, { label: 'System Settings', icon: <Settings size={19} /> },
];
const revenueData = [{ name: 'Mon', revenue: 15000, bookings: 120 }, { name: 'Tue', revenue: 18000, bookings: 150 }, { name: 'Wed', revenue: 22000, bookings: 180 }, { name: 'Thu', revenue: 17000, bookings: 140 }, { name: 'Fri', revenue: 32000, bookings: 250 }, { name: 'Sat', revenue: 45000, bookings: 320 }, { name: 'Sun', revenue: 38000, bookings: 280 }];
const initialVehicles: Vehicle[] = [{ id: 'BUS-101', plate: 'PB-10-AB-1234', type: 'AC Seater', seats: 42, status: 'En Route' }, { id: 'BUS-104', plate: 'PB-13-GH-8821', type: 'Volvo AC', seats: 44, status: 'Active' }, { id: 'BUS-209', plate: 'PB-22-KL-1088', type: 'Non-AC Seater', seats: 52, status: 'Active' }, { id: 'BUS-315', plate: 'PB-31-MN-4412', type: 'Sleeper', seats: 30, status: 'Maintenance' }, { id: 'BUS-402', plate: 'PB-40-QR-7770', type: 'Electric AC', seats: 40, status: 'Active' }];
const drivers: Driver[] = [{ name: 'Rajesh Kumar', id: 'D-014', phone: '+91 98765 43210', expiry: '12 Mar 2028', route: 'Patiala → Chandigarh', duty: 'On Shift', rating: '4.9' }, { name: 'Amit Singh', id: 'D-088', phone: '+91 98111 20045', expiry: '04 Nov 2027', route: 'Delhi → Manali', duty: 'On Shift', rating: '4.7' }, { name: 'Gurpreet Kaur', id: 'D-031', phone: '+91 99887 12003', expiry: '19 Jun 2026', route: 'Chandigarh → Shimla', duty: 'Off Duty', rating: '4.8' }, { name: 'Vikram Malhotra', id: 'D-052', phone: '+91 98989 77661', expiry: '22 Jan 2029', route: 'Rajpura → Amritsar', duty: 'Off Duty', rating: '4.6' }];
const routes = [{ id: 'R-08', from: 'Patiala', to: 'Chandigarh', stops: ['Rajpura Bypass', 'Zirakpur'], fare: 650, modifier: 'Peak +10%' }, { id: 'R-14', from: 'Delhi', to: 'Manali', stops: ['Chandigarh', 'Mandi'], fare: 1450, modifier: 'Weekend +15%' }, { id: 'R-21', from: 'Chandigarh', to: 'Shimla', stops: ['Panchkula', 'Kalka'], fare: 850, modifier: 'None' }];

export default function AdminDashboard() {
  const [activeTab, setActiveTab] = useState<Tab>('Dashboard');
  const [vehicles, setVehicles] = useState(initialVehicles);
  const [vehicleFilter, setVehicleFilter] = useState('All');
  const [vehicleSearch, setVehicleSearch] = useState('');
  const [isBusModalOpen, setIsBusModalOpen] = useState(false);
  const [toast, setToast] = useState('');
  const [routeStops, setRouteStops] = useState(['Rajpura Bypass', 'Zirakpur']);
  const [newStop, setNewStop] = useState('');
  const [scheduleCheck, setScheduleCheck] = useState<'IDLE' | 'CONFLICT' | 'PUBLISHED'>('IDLE');
  const [reportRange, setReportRange] = useState('Last 7 days');
  const [commission, setCommission] = useState('8');
  const [tax, setTax] = useState('5');

  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2500); };
  const filteredVehicles = vehicles.filter((vehicle) => (vehicleFilter === 'All' || vehicle.status === vehicleFilter) && `${vehicle.id} ${vehicle.plate} ${vehicle.type}`.toLowerCase().includes(vehicleSearch.toLowerCase()));
  const publishSchedule = (event: React.FormEvent) => { event.preventDefault(); setScheduleCheck('CONFLICT'); };
  const addStop = () => { if (newStop.trim()) { setRouteStops((stops) => [...stops, newStop.trim()]); setNewStop(''); } };

  return <div className="flex min-h-screen bg-[#080d1c] font-sans text-slate-100">
    <aside className="hidden w-72 shrink-0 border-r border-white/10 bg-[#0b1225] md:flex md:flex-col"><div className="flex items-center gap-3 border-b border-white/10 px-6 py-6"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500 text-slate-950"><Bus size={23} /></span><div><p className="text-lg font-extrabold">Omni<span className="text-blue-400">Admin</span></p><p className="text-[10px] font-bold uppercase tracking-widest text-slate-500">Operations centre</p></div></div><nav className="flex-1 space-y-1 p-4">{tabs.map((tab) => <NavItem key={tab.label} {...tab} active={activeTab === tab.label} onClick={() => setActiveTab(tab.label)} />)}</nav><div className="m-4 rounded-2xl border border-white/10 bg-[#10182d] p-4"><div className="flex items-center gap-2 text-emerald-400"><span className="h-2 w-2 rounded-full bg-emerald-400" /> Systems online</div><p className="mt-2 text-xs text-slate-500">All services operational</p></div></aside>
    <main className="min-w-0 flex-1 overflow-y-auto"><header className="sticky top-0 z-20 border-b border-white/10 bg-[#080d1c]/90 px-5 py-4 backdrop-blur sm:px-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-400">OmniAdmin / {activeTab}</p><h1 className="mt-1 text-2xl font-extrabold sm:text-3xl">{activeTab}</h1></div><div className="flex items-center gap-3"><span className="hidden text-right sm:block"><strong className="block text-sm">Super Admin</strong><small className="text-xs text-slate-500">admin@omnibus.in</small></span><span className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-500/15 text-blue-300"><UserRound size={19} /></span></div></div><div className="mt-4 flex gap-2 overflow-x-auto md:hidden">{tabs.map((tab) => <button key={tab.label} type="button" onClick={() => setActiveTab(tab.label)} className={`flex shrink-0 items-center gap-2 rounded-full px-3 py-2 text-xs font-bold ${activeTab === tab.label ? 'bg-blue-500 text-slate-950' : 'bg-[#10182d] text-slate-400'}`}>{tab.icon}{tab.label}</button>)}</div></header><div className="p-5 sm:p-8">{activeTab === 'Dashboard' && <Dashboard onPublish={() => { setScheduleCheck('PUBLISHED'); notify('Schedule published successfully'); }} scheduleCheck={scheduleCheck} />} {activeTab === 'Fleet Management' && <Fleet vehicles={filteredVehicles} search={vehicleSearch} setSearch={setVehicleSearch} filter={vehicleFilter} setFilter={setVehicleFilter} onAdd={() => setIsBusModalOpen(true)} onDelete={(id) => { setVehicles((current) => current.filter((vehicle) => vehicle.id !== id)); notify('Vehicle removed from fleet'); }} />} {activeTab === 'Routes & Stops' && <Routes stops={routeStops} newStop={newStop} setNewStop={setNewStop} addStop={addStop} onSave={() => notify('Route and pricing rules saved')} />} {activeTab === 'Drivers' && <Drivers />} {activeTab === 'Schedules' && <Schedules onCheck={publishSchedule} result={scheduleCheck} />} {activeTab === 'Reports' && <Reports range={reportRange} setRange={setReportRange} onExport={(type) => notify(`${type} export prepared`)} />} {activeTab === 'System Settings' && <SettingsView commission={commission} setCommission={setCommission} tax={tax} setTax={setTax} onSave={() => notify('Platform settings saved')} />}</div></main>{toast && <div className="fixed bottom-6 right-6 z-50 flex items-center gap-2 rounded-full bg-emerald-500 px-5 py-3 text-sm font-bold text-slate-950 shadow-xl"><Check size={17} />{toast}</div>}{isBusModalOpen && <BusModal onClose={() => setIsBusModalOpen(false)} onSave={(vehicle) => { setVehicles((current) => [...current, vehicle]); setIsBusModalOpen(false); notify('New bus added to fleet'); }} />}</div>;
}

function NavItem({ icon, label, active, onClick }: { icon: React.ReactNode; label: Tab; active: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-bold transition ${active ? 'bg-blue-500 text-slate-950 shadow-lg shadow-blue-950/30' : 'text-slate-400 hover:bg-white/5 hover:text-white'}`}>{icon}{label}</button>; }

function Dashboard({ onPublish, scheduleCheck }: { onPublish: () => void; scheduleCheck: string }) { return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat title="Active buses" value="128" detail="Out of 156 total" icon={<Activity />} tone="blue" /><Stat title="Today's bookings" value="1,440" detail="+12% from yesterday" icon={<TrendingUp />} tone="green" /><Stat title="Avg occupancy" value="84%" detail="Across all routes" icon={<Users />} tone="violet" /><Stat title="Delayed trips" value="3" detail="Requires attention" icon={<AlertTriangle />} tone="amber" /></div><div className="grid gap-6 xl:grid-cols-[1.4fr_0.6fr]"><Panel title="Weekly revenue trends" icon={<TrendingUp className="text-blue-400" />}><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenueData}><defs><linearGradient id="revenue-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#60a5fa" stopOpacity={0.35} /><stop offset="100%" stopColor="#60a5fa" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#24324d" /><XAxis dataKey="name" stroke="#64748b" axisLine={false} tickLine={false} /><YAxis stroke="#64748b" axisLine={false} tickLine={false} tickFormatter={(value) => `₹${value / 1000}k`} /><Tooltip contentStyle={{ background: '#10182d', border: '1px solid #334155', borderRadius: 12 }} /><Area type="monotone" dataKey="revenue" stroke="#60a5fa" strokeWidth={3} fill="url(#revenue-fill)" /></AreaChart></ResponsiveContainer></div></Panel><Panel title="Schedule dispatcher" icon={<CalendarDays className="text-blue-400" />}><form onSubmit={(event) => { event.preventDefault(); onPublish(); }} className="space-y-4"><Select label="Select bus" options={['BUS-104 · Volvo AC', 'BUS-209 · Local', 'BUS-402 · Electric AC']} /><Select label="Select driver" options={['D-014 · Rajesh Kumar', 'D-088 · Amit Singh']} /><Select label="Time slot" options={['Today · 10:00 AM - 1:00 PM', 'Today · 2:00 PM - 5:00 PM']} /><button className="btn-pill btn-primary w-full py-3">Publish schedule <ArrowRight size={17} /></button></form>{scheduleCheck === 'PUBLISHED' && <p className="mt-4 rounded-xl bg-emerald-500/10 p-3 text-sm font-bold text-emerald-300">Schedule published and drivers notified.</p>}</Panel></div></div>; }

function Fleet({ vehicles, search, setSearch, filter, setFilter, onAdd, onDelete }: { vehicles: Vehicle[]; search: string; setSearch: (value: string) => void; filter: string; setFilter: (value: string) => void; onAdd: () => void; onDelete: (id: string) => void }) { return <Panel title="Fleet inventory" icon={<Bus className="text-blue-400" />} action={<button onClick={onAdd} className="btn-pill btn-primary px-4 py-2 text-sm"><Plus size={16} /> Add new bus</button>}><div className="mb-5 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search size={17} className="absolute left-3 top-3 text-slate-500" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search bus ID, plate or type" className="h-11 w-full rounded-xl border border-white/10 bg-[#0b1225] pl-10 pr-4 text-sm text-white outline-none focus:border-blue-400" /></label><select value={filter} onChange={(event) => setFilter(event.target.value)} className="h-11 rounded-xl border border-white/10 bg-[#0b1225] px-4 text-sm text-slate-300 outline-none"><option>All</option><option>Active</option><option>En Route</option><option>Maintenance</option></select></div><Table><thead><tr><Th>Bus ID</Th><Th>License plate</Th><Th>Bus type</Th><Th>Seats</Th><Th>Status</Th><Th>Actions</Th></tr></thead><tbody>{vehicles.map((vehicle) => <tr key={vehicle.id} className="border-t border-white/10"><Td strong>{vehicle.id}</Td><Td mono>{vehicle.plate}</Td><Td>{vehicle.type}</Td><Td>{vehicle.seats}</Td><Td><Status label={vehicle.status} /></Td><Td><div className="flex gap-2"><button className="rounded-lg p-2 text-slate-500 hover:bg-white/10 hover:text-blue-300"><Edit3 size={16} /></button><button onClick={() => onDelete(vehicle.id)} className="rounded-lg p-2 text-slate-500 hover:bg-red-500/10 hover:text-red-300"><Trash2 size={16} /></button></div></Td></tr>)}</tbody></Table></Panel>; }

function Routes({ stops, newStop, setNewStop, addStop, onSave }: { stops: string[]; newStop: string; setNewStop: (value: string) => void; addStop: () => void; onSave: () => void }) { return <div className="grid gap-6 xl:grid-cols-[1fr_0.8fr]"><Panel title="Route builder" icon={<Route className="text-blue-400" />}><div className="grid gap-4 sm:grid-cols-2"><Input label="Origin" value="Patiala Bus Stand" /><Input label="Destination" value="ISBT Sec 43 Chandigarh" /></div><div className="mt-6"><p className="mb-3 text-sm font-bold text-slate-300">Waypoint manager</p><div className="space-y-3">{stops.map((stop, index) => <div key={stop} className="flex items-center gap-3 rounded-xl border border-white/10 bg-[#0b1225] p-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-blue-500/15 text-xs font-bold text-blue-300">{index + 1}</span><span className="flex-1 text-sm font-bold">{stop}</span><span className="text-xs text-slate-500">{index === 0 ? '35 min · 28 km' : '20 min · 12 km'}</span><button onClick={() => setNewStop(stop)} className="text-slate-500 hover:text-white"><X size={15} /></button></div>)}</div><div className="mt-3 flex gap-2"><input value={newStop} onChange={(event) => setNewStop(event.target.value)} placeholder="Add intermediate stop" className="h-11 min-w-0 flex-1 rounded-xl border border-white/10 bg-[#0b1225] px-4 text-sm text-white outline-none focus:border-blue-400" /><button type="button" onClick={addStop} className="btn-pill btn-secondary px-4"><Plus size={17} /> Add</button></div></div></Panel><Panel title="Pricing engine" icon={<CircleDollarSign className="text-emerald-400" />}><Input label="Base fare (₹)" value="650" /><Input label="Dynamic pricing modifier" value="Peak hours +10%" /><Input label="Distance (km)" value="48" /><button onClick={onSave} className="btn-pill btn-primary mt-5 w-full py-3">Save route rules <Check size={17} /></button></Panel></div>; }

function Drivers() { return <Panel title="Driver roster" icon={<Users className="text-blue-400" />}><Table><thead><tr><Th>Driver</Th><Th>Contact</Th><Th>License expiry</Th><Th>Assigned route</Th><Th>Duty</Th><Th>Rating</Th></tr></thead><tbody>{drivers.map((driver) => <tr key={driver.id} className="border-t border-white/10"><Td strong>{driver.name}<span className="mt-1 block text-xs font-normal text-slate-500">{driver.id}</span></Td><Td>{driver.phone}</Td><Td>{driver.expiry}</Td><Td>{driver.route}</Td><Td><Status label={driver.duty} /></Td><Td><span className="font-bold text-amber-300">★ {driver.rating}</span></Td></tr>)}</tbody></Table></Panel>; }

function Schedules({ onCheck, result }: { onCheck: (event: React.FormEvent) => void; result: string }) { return <div className="space-y-6"><Panel title="Today's dispatch timeline" icon={<CalendarDays className="text-blue-400" />}><div className="space-y-3">{[['06:00 AM', 'BUS-101', 'Patiala → Chandigarh', 'Rajesh Kumar', 'On time'], ['08:30 AM', 'BUS-209', 'Patiala → Chandigarh', 'Amit Singh', 'On time'], ['12:00 PM', 'BUS-315', 'Delhi → Manali', 'Gurpreet Kaur', 'Conflict']].map(([time, bus, route, driver, status]) => <div key={time} className={`grid gap-3 rounded-xl border p-4 sm:grid-cols-[90px_110px_1fr_160px_100px] sm:items-center ${status === 'Conflict' ? 'border-red-400/40 bg-red-500/10' : 'border-white/10 bg-[#0b1225]'}`}><span className="font-mono text-sm font-bold text-blue-300">{time}</span><span className="font-bold">{bus}</span><span className="text-sm text-slate-300">{route}</span><span className="text-sm text-slate-400">{driver}</span><span className={status === 'Conflict' ? 'font-bold text-red-300' : 'font-bold text-emerald-300'}>{status}</span></div>)}</div></Panel><Panel title="Conflict resolution" icon={<AlertTriangle className="text-amber-400" />}><form onSubmit={onCheck} className="flex flex-col gap-4 sm:flex-row sm:items-end"><Select label="Driver" options={['Gurpreet Kaur · D-031', 'Rajesh Kumar · D-014']} /><Select label="Overlapping trip" options={['12:00 PM · Delhi → Manali', '12:30 PM · Chandigarh → Shimla']} /><button className="btn-pill btn-primary min-h-11 px-5">Validate assignment</button></form>{result === 'CONFLICT' && <p className="mt-4 rounded-xl border border-red-400/20 bg-red-500/10 p-4 text-sm font-bold text-red-300">Conflict detected: Gurpreet Kaur is assigned to two overlapping trips. Reassign one trip before publishing.</p>}</Panel></div>; }

function Reports({ range, setRange, onExport }: { range: string; setRange: (value: string) => void; onExport: (type: string) => void }) { return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm text-slate-400">Financial and operations summary</p><h2 className="mt-1 text-xl font-extrabold">Performance reports</h2></div><div className="flex gap-2"><select value={range} onChange={(event) => setRange(event.target.value)} className="rounded-xl border border-white/10 bg-[#10182d] px-4 py-2.5 text-sm text-slate-300"><option>Last 7 days</option><option>This month</option><option>Custom date</option></select><button onClick={() => onExport('CSV')} className="btn-pill btn-secondary px-4 py-2 text-sm"><Download size={16} /> CSV</button><button onClick={() => onExport('PDF')} className="btn-pill btn-secondary px-4 py-2 text-sm"><FileText size={16} /> PDF</button></div></div><div className="grid gap-4 sm:grid-cols-3"><Stat title="Gross ticket sales" value="₹12.8L" detail={range} icon={<CircleDollarSign />} tone="green" /><Stat title="Platform fees" value="₹1.02L" detail="8% commission" icon={<TrendingUp />} tone="blue" /><Stat title="Tax liabilities" value="₹64,000" detail="5% GST" icon={<FileText />} tone="amber" /></div><Panel title="Financial breakdown" icon={<BarChart3 className="text-blue-400" />}><Table><thead><tr><Th>Day</Th><Th>Gross sales</Th><Th>Platform fees</Th><Th>Tax liability</Th><Th>Net settlement</Th></tr></thead><tbody>{revenueData.slice(0, 5).map((day) => <tr key={day.name} className="border-t border-white/10"><Td strong>{day.name}, 03 Sep</Td><Td>₹{day.revenue.toLocaleString('en-IN')}</Td><Td>₹{(day.revenue * 0.08).toLocaleString('en-IN')}</Td><Td>₹{(day.revenue * 0.05).toLocaleString('en-IN')}</Td><Td strong>₹{(day.revenue * 0.87).toLocaleString('en-IN')}</Td></tr>)}</tbody></Table></Panel></div>; }

function SettingsView({ commission, setCommission, tax, setTax, onSave }: { commission: string; setCommission: (value: string) => void; tax: string; setTax: (value: string) => void; onSave: () => void }) { return <div className="grid gap-6 xl:grid-cols-[1fr_0.8fr]"><Panel title="Platform configuration" icon={<Settings className="text-blue-400" />}><div className="space-y-5"><Input label="Default platform commission (%)" value={commission} onChange={setCommission} /><Input label="GST / tax rate (%)" value={tax} onChange={setTax} /><label className="block text-sm font-bold text-slate-300">Terms & conditions<textarea defaultValue="Tickets are subject to operator availability and cancellation policies." className="mt-2 min-h-32 w-full rounded-xl border border-white/10 bg-[#0b1225] p-4 text-sm text-white outline-none focus:border-blue-400" /></label><button onClick={onSave} className="btn-pill btn-primary px-5 py-3">Save configuration <Check size={17} /></button></div></Panel><Panel title="Access control" icon={<ShieldCheck className="text-emerald-400" />}><div className="space-y-3">{[['Super Admin', 'Full platform access'], ['Dispatcher', 'Fleet and schedule management'], ['Support Staff', 'Bookings and passenger support']].map(([role, access]) => <div key={role} className="flex items-center gap-3 rounded-xl border border-white/10 bg-[#0b1225] p-4"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-emerald-400/10 text-emerald-300"><ShieldCheck size={17} /></span><span className="flex-1"><strong className="block text-sm">{role}</strong><small className="text-xs text-slate-500">{access}</small></span><button className="text-slate-500 hover:text-blue-300"><Edit3 size={16} /></button></div>)}</div><button className="btn-pill btn-secondary mt-5 px-4 py-2 text-sm"><Plus size={16} /> Add admin role</button></Panel></div>; }

function BusModal({ onClose, onSave }: { onClose: () => void; onSave: (vehicle: Vehicle) => void }) { const [id, setId] = useState('BUS-'); const [plate, setPlate] = useState(''); const [type, setType] = useState('AC Seater'); return <Modal title="Add new bus" onClose={onClose}><div className="space-y-4"><Input label="Bus ID" value={id} onChange={setId} /><Input label="License plate" value={plate} onChange={setPlate} placeholder="PB-00-AA-0000" /><Select label="Bus type" options={['AC Seater', 'Volvo AC', 'Sleeper', 'Electric AC']} value={type} onChange={setType} /><button onClick={() => onSave({ id, plate: plate || 'PB-00-AA-0000', type, seats: 42, status: 'Active' })} className="btn-pill btn-primary w-full py-3">Add vehicle</button></div></Modal>; }

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 px-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-[#10182d] p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-extrabold">{title}</h2><button onClick={onClose} className="rounded-full p-2 text-slate-400 hover:bg-white/10 hover:text-white"><X size={19} /></button></div>{children}</div></div>; }
function LiveTripPanel() {
  const [trip, setTrip] = useState<{ status: string; vehicleId: string; from: string; to: string; currentStopIndex: number; stops: string[]; passengers: { boarded: boolean }[]; updatedAt: string } | null>(null);

  useEffect(() => {
    const loadTrip = () => fetch('/api/trip', { cache: 'no-store' }).then((response) => response.json()).then(setTrip).catch(() => undefined);
    loadTrip();
    const intervalId = window.setInterval(loadTrip, 5000);
    return () => window.clearInterval(intervalId);
  }, []);

  const boardedCount = trip?.passengers.filter((passenger) => passenger.boarded).length ?? 0;
  const status = trip?.status ?? 'SCHEDULED';
  return <section className="rounded-3xl border border-blue-400/20 bg-blue-400/10 p-5 shadow-2xl shadow-black/20 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-300">Live operations</p><h2 className="mt-1 text-lg font-extrabold">{trip ? `${trip.vehicleId} · ${trip.from} to ${trip.to}` : 'Loading active trip...'}</h2><p className="mt-1 text-sm text-slate-400">Current stop: {trip?.stops[trip.currentStopIndex] ?? 'Loading trip state...'}</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${status === 'RUNNING' ? 'bg-emerald-400/15 text-emerald-300' : status === 'DELAYED' ? 'bg-amber-400/15 text-amber-300' : status === 'COMPLETED' ? 'bg-slate-700 text-slate-300' : 'bg-amber-400/15 text-amber-300'}`}>{status}</span></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-4"><p className="text-sm font-bold text-slate-300">{boardedCount}/{trip?.passengers.length ?? 0} passengers boarded</p><a href="/track" className="btn-pill btn-secondary px-4 py-2 text-xs">Open live tracking <ArrowRight size={15} /></a></div></section>; }

function Panel({ title, icon, action, children }: { title: string; icon?: React.ReactNode; action?: React.ReactNode; children: React.ReactNode }) { return <>{title === 'Weekly revenue trends' && <LiveTripPanel />}<section className="rounded-3xl border border-white/10 bg-[#10182d] p-5 shadow-2xl shadow-black/20 sm:p-6"><div className="mb-6 flex items-center justify-between gap-3"><h2 className="flex items-center gap-2 text-lg font-extrabold">{icon}{title}</h2>{action}</div>{children}</section></>; }
function Stat({ title, value, detail, icon, tone }: { title: string; value: string; detail: string; icon: React.ReactNode; tone: string }) { return <div className="rounded-2xl border border-white/10 bg-[#10182d] p-5"><div className="flex items-center justify-between"><p className="text-sm font-bold text-slate-400">{title}</p><span className={`rounded-xl p-2 ${tone === 'green' ? 'bg-emerald-400/10 text-emerald-300' : tone === 'amber' ? 'bg-amber-400/10 text-amber-300' : tone === 'violet' ? 'bg-violet-400/10 text-violet-300' : 'bg-blue-400/10 text-blue-300'}`}>{icon}</span></div><p className="mt-5 text-3xl font-extrabold">{value}</p><p className="mt-1 text-xs font-semibold text-slate-500">{detail}</p></div>; }
function Status({ label }: { label: string }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${label === 'Maintenance' || label === 'Conflict' ? 'bg-red-400/10 text-red-300' : label === 'En Route' || label === 'On Shift' ? 'bg-blue-400/10 text-blue-300' : label === 'Off Duty' ? 'bg-slate-700 text-slate-300' : 'bg-emerald-400/10 text-emerald-300'}`}>{label}</span>; }
function Select({ label, options, value, onChange }: { label: string; options: string[]; value?: string; onChange?: (value: string) => void }) { return <label className="block flex-1 text-sm font-bold text-slate-300">{label}<span className="relative mt-2 block"><select value={value} onChange={(event) => onChange?.(event.target.value)} className="h-11 w-full appearance-none rounded-xl border border-white/10 bg-[#0b1225] px-4 pr-9 text-sm text-white outline-none focus:border-blue-400">{options.map((option) => <option key={option}>{option}</option>)}</select><ChevronDown size={16} className="pointer-events-none absolute right-3 top-3.5 text-slate-500" /></span></label>; }
function Input({ label, value, onChange, placeholder }: { label: string; value: string; onChange?: (value: string) => void; placeholder?: string }) { return <label className="block text-sm font-bold text-slate-300">{label}<input value={value} onChange={(event) => onChange?.(event.target.value)} placeholder={placeholder} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-[#0b1225] px-4 text-sm text-white outline-none placeholder:text-slate-600 focus:border-blue-400" /></label>; }
function Table({ children }: { children: React.ReactNode }) { return <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm">{children}</table></div>; }
function Th({ children }: { children: React.ReactNode }) { return <th className="whitespace-nowrap px-4 pb-3 text-xs font-bold uppercase tracking-wider text-slate-500 first:pl-0">{children}</th>; }
function Td({ children, strong, mono }: { children: React.ReactNode; strong?: boolean; mono?: boolean }) { return <td className={`whitespace-nowrap px-4 py-4 text-slate-400 first:pl-0 ${strong ? 'font-bold text-white' : ''} ${mono ? 'font-mono text-xs' : ''}`}>{children}</td>; }
